Add test CI (#142)
* WIP: add ci tests

* force ci tests

access token should work now

* force tests

* add pip install to tests

* test add postgres

* put postgres in container 

db_finder.py expects a container so...

* indent lives matter

* run the db locally in test

* fix docker-compose command

with previous command `run db`, the workflow stalls.

* add postgres password as env var

* change docker-compose up to run

* replace test using python to full docker-compose

* remove python strategy

* test fix "the input device is not a TTY"

the input device is not a TTY
Error: Process completed with exit code 1.
https://github.com/IFB-ElixirFr/ifbcat/runs/1818228578

* fix email adress and add migrate

https://github.com/IFB-ElixirFr/ifbcat/runs/1818292328

* fix "You must use --firstname"

https://github.com/IFB-ElixirFr/ifbcat/runs/1818324019

CommandError: You must use --firstname with --noinput.

* fix "the input device is not a TTY"

It seems all exec commands should be run with "-T"
https://github.com/IFB-ElixirFr/ifbcat/runs/1818381843

* fix migrate before createsuperuser

https://github.com/IFB-ElixirFr/ifbcat/runs/1818402374

* test fix migrate


https://github.com/IFB-ElixirFr/ifbcat/runs/1818433292

* test debug migrations



rm: cannot remove 'ifbcat_api/migrations/__pycache__/0066_auto_20200813_1004.cpython-37.pyc': Permission denied

* test without migrate